//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace psbizsuite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountReceivable
    {
        public int AccountReceivableId { get; set; }
        public string Status { get; set; }
        public double TotalAmount { get; set; }
        public int Order_OrderId { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
