//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class InventoryItem
{
	public virtual string description
	{
		get;
		set;
	}

	public virtual int id
	{
		get;
		set;
	}

	public virtual Double quantity
	{
		get;
		set;
	}

	public virtual Double unitCost
	{
		get;
		set;
	}

	public virtual Double unitWeightKilo
	{
		get;
		set;
	}

	public virtual Account Account
	{
		get;
		set;
	}

    public void reduceQuantity(int quantity)
    {
        this.quantity -= quantity;
    }

    public void replenishStock(int quantity)
    {
        this.quantity += quantity;
    }

    public bool isExist()
    {
        return (this == null) ? false : true;
    }

}

