//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Inventory
{
	public virtual DateTime date
	{
		get;
		set;
	}

	public virtual int id
	{
		get;
		set;
	}

	public virtual IEnumerable<InventoryItem> InventoryItem
	{
		get;
		set;
	}

}

