//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace psbizsuite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Inventory
    {
        public int InventoryId { get; set; }
        [Required(ErrorMessage = "Itemname field is required!")]
        public string ItemName { get; set; }
        public string ItemDescription { get; set; }
        public byte[] Image { get; set; }
        public decimal UnitCost { get; set; }
        public Nullable<decimal> UnitWeightKilo { get; set; }
        [Required(ErrorMessage = "Please make sure quantity is a valid whole number!")]
        public int Quantity { get; set; }
        public string Location { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string Supplier_UserAccount_Username { get; set; }
        public int Category_CatId { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public virtual category category { get; set; }
    }
}
