//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace psbizsuite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveRequest
    {
        public int LeaveRequestId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Reason { get; set; }
        public string Employee_UserAccount_Username { get; set; }
        public int LeavePolicy_LeavePolicyId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual LeavePolicy LeavePolicy { get; set; }
    }
}
