//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace psbizsuite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeavePolicy
    {
        public LeavePolicy()
        {
            this.LeaveRequests = new HashSet<LeaveRequest>();
        }
    
        public int LeavePolicyId { get; set; }
        public string PolicyName { get; set; }
        public string PolicyDescription { get; set; }
        public int DaysOfLeave { get; set; }
        public double MinServiceYear { get; set; }
        public bool Paid { get; set; }
        public string Period { get; set; }
    
        public virtual ICollection<LeaveRequest> LeaveRequests { get; set; }
    }
}
