//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace psbizsuite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderItems = new HashSet<OrderItem>();
            this.invoices = new HashSet<invoice>();
        }
    
        public int OrderId { get; set; }
        public int ReceiptId { get; set; }
        public string Status { get; set; }
        public string Customer_UserAccount_Username { get; set; }
        public double TotalAmount { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual ICollection<invoice> invoices { get; set; }
    }
}
