//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class OrderItem
{
	public virtual int id
	{
		get;
		set;
	}

	public virtual string description
	{
		get;
		set;
	}

	public virtual Double unitPrice
	{
		get;
		set;
	}

	public virtual Double quantity
	{
		get;
		set;
	}

	public virtual Double totalAmount
	{
		get;
		set;
	}

}

