//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Payroll
{
	public virtual Double amount
	{
		get;
		set;
	}

	public virtual Double totalWorkingHour
	{
		get;
		set;
	}

	public virtual Double totalOTHour
	{
		get;
		set;
	}

	public virtual IEnumerable<Attendance> Attendance
	{
		get;
		set;
	}

}

