//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace psbizsuite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchasetype
    {
        public purchasetype()
        {
            this.purchases = new HashSet<purchase>();
        }
    
        public int PurchaseTypeID { get; set; }
        public string Name { get; set; }
        public string Descr { get; set; }
    
        public virtual ICollection<purchase> purchases { get; set; }
    }
}
