//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace psbizsuite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase
    {
        public int PurchaseID { get; set; }
        public string Article { get; set; }
        public double Price { get; set; }
        public double VAT { get; set; }
        public string Notes { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public double AdvancePaymentTax { get; set; }
        public string Supplier_UserAccount_Username { get; set; }
        public int Purchasetype_PurchaseTypeID { get; set; }
    
        public virtual Supplier supplier { get; set; }
        public virtual purchasetype purchasetype { get; set; }
    }
}
