//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class SupportTicket
{
	public virtual int id
	{
		get;
		set;
	}

	public virtual string answer
	{
		get;
		set;
	}

	public virtual int referenceId
	{
		get;
		set;
	}

	public virtual Customer Customer
	{
		get;
		set;
	}

}

