//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Account
{
	public virtual Double cashInAmount
	{
		get;
		set;
	}

	public virtual Double cashOutAmount
	{
		get;
		set;
	}

	public virtual int invoiceId
	{
		get;
		set;
	}

	public virtual int plStatementId
	{
		get;
		set;
	}

	public virtual DateTime timeStamp
	{
		get;
		set;
	}

	public virtual Order Order
	{
		get;
		set;
	}

	public virtual IEnumerable<InventoryItem> InventoryItem
	{
		get;
		set;
	}

	public virtual IEnumerable<PayrollRequest> PayrollRequest
	{
		get;
		set;
	}

}

