//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace psbizsuite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Attendances = new HashSet<Attendance>();
            this.KeyPairs = new HashSet<KeyPair>();
            this.LeaveRequests = new HashSet<LeaveRequest>();
            this.SupportTickets = new HashSet<SupportTicket>();
        }
    
        public string FullName { get; set; }
        public string Address { get; set; }
        public int PhoneNo { get; set; }
        public string NRIC { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime? DOB { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> EndEmploymentDate { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime? StartEmploymentDate { get; set; }
        public double SalaryPerHour { get; set; }
        [Required(ErrorMessage = "Is required field. Format HH:MM (24 hour time)")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:hh\\:mm}")]
        public System.TimeSpan StartShiftHour { get; set; }
        [Required(ErrorMessage = "Is required field. Format HH:MM (24 hour time)")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:hh\\:mm}")]
        public System.TimeSpan EndShirtHour { get; set; }
        public string UserAccount_Username { get; set; }
        public string EmployeePosition_PositionName { get; set; }

        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual EmployeePosition EmployeePosition { get; set; }
        public virtual UserAccount UserAccount { get; set; }
        public virtual ICollection<KeyPair> KeyPairs { get; set; }
        public virtual ICollection<LeaveRequest> LeaveRequests { get; set; }
        public virtual ICollection<SupportTicket> SupportTickets { get; set; }
    }
}
