//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace psbizsuite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int InventoryId { get; set; }
        public string ItemDescription { get; set; }
        public string Image { get; set; }
        public string UnitCost { get; set; }
        public string UnitWeightKilo { get; set; }
        public string Quantity { get; set; }
        public string Location { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string Supplier_UserAccount_Username { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public virtual Category Category { get; set; }
    }
}
