//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Leave
{
	public virtual DateTime startLeaveDate
	{
		get;
		set;
	}

	public virtual string status
	{
		get;
		set;
	}

	public virtual string reason
	{
		get;
		set;
	}

	public virtual DateTime endLeaveDate
	{
		get;
		set;
	}

	public virtual string policyType
	{
		get;
		set;
	}

	public virtual Employee Employee
	{
		get;
		set;
	}

}

