//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace psbizsuite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class LeaveRequest
    {
        public int LeaveRequestId { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public System.DateTime StartDate { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public System.DateTime EndDate { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string Reason { get; set; }
        public string Employee_UserAccount_Username { get; set; }
        public int LeavePolicy_LeavePolicyId { get; set; }
        public string Status { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual LeavePolicy leavepolicy { get; set; }
    }
}
