//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Order
{
	public virtual int id
	{
		get;
		set;
	}

	public virtual int receiptId
	{
		get;
		set;
	}

	public virtual string status
	{
		get;
		set;
	}

	public virtual Customer Customer
	{
		get;
		set;
	}

	public virtual OrderItem OrderItem
	{
		get;
		set;
	}

}

