//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class PayrollRequest
{
	public virtual int id
	{
		get;
		set;
	}

	public virtual string status
	{
		get;
		set;
	}

	public virtual Double totalAmount
	{
		get;
		set;
	}

	public virtual DateTime date
	{
		get;
		set;
	}

	public virtual Account Account
	{
		get;
		set;
	}

	public virtual Employee Employee
	{
		get;
		set;
	}

}

