//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace psbizsuite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollRequest
    {
        public int PayrollRequestId { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public Nullable<System.DateTime> RequestTimeStamp { get; set; }
        public string Status { get; set; }
    }
}
