//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace psbizsuite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class profitloss
    {
        public int profitLossId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> Income { get; set; }
        public Nullable<double> Expenses { get; set; }
        public Nullable<double> CashOnHand { get; set; }
    }
}
