//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class User
{
	public virtual string username
	{
		get;
		set;
	}

	public virtual string password
	{
		get;
		set;
	}

	public virtual string address
	{
		get;
		set;
	}

	public virtual int phoneNo
	{
		get;
		set;
	}

	public virtual string email
	{
		get;
		set;
	}

	public virtual string fullName
	{
		get;
		set;
	}

}

